export const carousel_11 = {
  carousel: [
    {
      id: 1,
      title: "Everherb Karela Jamun Juice - Helps Maintaing",
      MRP: "MRP ₹399.00",
      price: "₹270.48",
      discount: "(48%)",
      image: require("../Assets/Carousel_assets/c-7/"),
    },
    {
      id: 2,
      title: "Liveasy Wellness Calcium Magnesium ",
      MRP: "MRP ₹599.00",
      price: "₹479.48",
      discount: "(20%)",
      image: require("./"),
    },
    {
      id: 3,
      title: "Pharmeasy All-in -one Vaporizer",
      MRP: "MRP ₹599.00",
      price: "₹269.55",
      discount: "(55%)",
      image: require("../Assets/Carousel_assets/c-7/"),
    },
    {
      id: 4,
      title: "Pharmeasy Calcium Magnesium Vitamin D",
      MRP: "MRP ₹499.00",
      price: "₹299.40",
      discount: "(40%)",
      image: require("./"),
    },
    {
      id: 5,
      title: "Pharmeasy Hot Water Bag - Relieves Pain",
      MRP: "MRP ₹349.00",
      price: "₹300.14",
      discount: "(14%)",
      image: require("../Assets/Carousel_assets/c-7/"),
    },
    {
      id: 6,
      title: "Liveasy Wellness Diabetic Protein",
      MRP: "MRP ₹999.00",
      price: "₹559.44",
      discount: "(44%)",
      image: require("./"),
    },
    {
      id: 7,
      title: "Pharmeasy Biotin 10000mcg ",
      MRP: "MRP ₹699.00",
      price: "₹384.44",
      discount: "(45%)",

      image: require("../Assets/Carousel_assets/c-7/"),
    },
    {
      id: 8,
      title: "Liveasy Foods Healthy Roasted Seed Mix",
      MRP: "MRP ₹399.00",
      price: "₹219.45",
      discount: "(45%)",
      image: require("./"),
    },
    {
      id: 9,
      title: "Liveasy Foods Roasted Peri Peri Makhana",
      MRP: "MRP ₹299.00",
      price: "₹164.45",
      discount: "(45%)",
      image: require("./"),
    },
    {
      id: 10,
      title: "Liveasy Essentials Copper Bottle",
      MRP: "MRP ₹1199.00",
      price: "₹839.30",
      discount: "(30%)",
      image: require("./"),
    },
  ],
};
