export const carousel_7 = {
  carousel: [
    {
      id: 1,
      title: "Shelcal 500mg Strip Of 15 Tablets",
      MRP: "MRP ₹399.00",
      price: "₹270.48",
      discount: "(7%)",
      image: require("../Assets/Carousel_assets/c-7/"),
    },
    {
      id: 2,
      title: "Everherb Karela Jamun Juice - ",
      MRP: "MRP ₹399.00",
      price: "₹270.48",
      discount: "(7%)",
      image: require("./"),
    },
    {
      id: 3,
      title: "Accu-Chek Active Glucometer Test Strips Box Of 50",
      MRP: "MRP ₹1049.00",
      price: "₹1038.51",
      discount: "(1%)",
      image: require("../Assets/Carousel_assets/c-7/"),
    },
    {
      id: 4,
      title: "Dr. Morepen Gluco One Bg 03 Glucometer Test Strips",
      MRP: "MRP ₹849.00",
      price: "₹721.65",
      discount: "(15%)",
      image: require("./"),
    },
    {
      id: 5,
      title: "Pharmeasy All-in -one Vaporizer",
      MRP: "MRP ₹599.00",
      price: "₹269.55",
      discount: "(55%)",
      image: require("../Assets/Carousel_assets/c-7/"),
    },
    {
      id: 6,
      title: "Acne Uv Spf 50 Gel 50gm",
      MRP: "MRP ₹875.00",
      price: "₹778.75",
      discount: "(11%)",
      image: require("./"),
    },
    {
      id: 7,
      title: "Liveasy Essentials Waterproof Bandages",
      MRP: "MRP ₹249.00",

      image: require("../Assets/Carousel_assets/c-7/"),
    },
    {
      id: 8,
      title: "I-Pill Emergency Contraceptive Pill",
      MRP: "MRP ₹110.00",
      price: "₹99.00",
      discount: "(10%)",
      image: require("./"),
    },
    {
      id: 9,
      title: "Photostable Gold Spf55 Sunscreen Gel",
      MRP: "MRP ₹755.00",

      image: require("../Assets/Carousel_assets/c-7/"),
    },
    {
      id: 10,
      title: "Accu-chek Instant Glucometer Test Strip",
      MRP: "MRP ₹1049.00",
      price: "₹1038.51",
      discount: "(1%)",
      image: require("./"),
    },
    {
      id: 11,
      title: "Uv Doux Spf 50 Tube Of 50gm Sunscreen",
      MRP: "MRP ₹699.00",
      price: "₹601.14",
      discount: "(14%)",
      image: require("../Assets/Carousel_assets/c-7/"),
    },
    {
      id: 12,
      title: "Moisturex Cream 100gm",
      MRP: "MRP ₹275.00",
      price: "₹261.25",
      discount: "(5%)",
      image: require("./"),
    },
    {
      id: 13,
      title: "Saslic Face Wash 60ml",
      MRP: "MRP ₹399.99",
      price: "₹383.99",
      discount: "(4%)",
      image: require("./"),
    },
  ],
};
