export const carousel_8 = {
  carousel: [
    {
      id: 1,
      title: "Supradyn Immuno+ With Turmeric + Tulsi Natural",
      MRP: "MRP ₹270.00",
      price: "₹236.60",
      discount: "(12%)",
      image: require("../Assets/Carousel_assets/c-7/"),
    },
    {
      id: 2,
      title: "Glutone 1000mg Tablet 15'S",
      MRP: "MRP ₹2599.00",
      price: "₹2209.15",
      discount: "(15%)",
      image: require("./"),
    },
    {
      id: 3,
      title: "Nutriburst Hair Skin & Nails Gummies | Enriche",
      MRP: "MRP ₹1299.00",
      price: "₹519.99",
      discount: "(60%)",
      image: require("../Assets/Carousel_assets/c-7/"),
    },
    {
      id: 4,
      title: "Supradyn Immuno+ With Turmeric + Tulsi Natural",
      MRP: "MRP ₹270.00",
      price: "₹237.60",
      discount: "(12%)",
      image: require("./"),
    },
    {
      id: 5,
      title: "Omron Hem 6161 Fully Automatic Wrist Blood",
      MRP: "MRP ₹2345.00",
      price: "₹2040.15",
      discount: "(13%)",
      image: require("../Assets/Carousel_assets/c-7/"),
    },
    {
      id: 6,
      title: "Reshape Natural Health Supplement Tablets ",
      MRP: "MRP ₹403.00",
      price: "₹350.61",
      discount: "(13%)",
      image: require("./"),
    },
    {
      id: 7,
      title: "Gnc Triple Strength Fish Oil - 1500 Mg - 60 ",
      MRP: "MRP ₹1399.00",
      price: "₹965.31",
      discount: "(31%)",

      image: require("../Assets/Carousel_assets/c-7/"),
    },
    {
      id: 8,
      title: "Kapiva Himalayan Shilajit Resin - 20g",
      MRP: "MRP ₹1499.00",
      price: "₹949.02",
      discount: "(37%)",
      image: require("./"),
    },
    {
      id: 9,
      title: "Swisse Ultiboost Odourless Strength Wild",
      MRP: "MRP ₹2349.00",
      price: "₹1714.77",
      discount: "(27%)",

      image: require("../Assets/Carousel_assets/c-7/"),
    },
    {
      id: 10,
      title: "Calcimax Total Tablet 15'S",
      MRP: "MRP ₹344.00",
      price: "₹302.72",
      discount: "(12%)",
      image: require("./"),
    },
    {
      id: 11,
      title: "Bpl Breathe Ezee N5 Compressor Nebulizer",
      MRP: "MRP ₹1620.00",
      price: "₹1377.00",
      discount: "(15%)",
      image: require("../Assets/Carousel_assets/c-7/"),
    },
    {
      id: 12,
      title: "Everherb (By Pharmeasy) Ashwagandha - Immunity",
      MRP: "MRP ₹599.00",
      price: "₹455.24",
      discount: "(24%)",
      image: require("./"),
    },
    {
      id: 13,
      title: "Healthkart Hk Vitals Fish Oil 1000mg With 180mg",
      MRP: "MRP ₹469.00",
      price: "₹267.00",
      discount: "(43%)",
      image: require("./"),
    },

    {
      id: 14,
      title: "Gnc Triflex Fast Acting - 120 Caplets",
      MRP: "MRP ₹4099.00",
      price: "₹2582.37",
      discount: "(37%)",
      image: require("./"),
    },

    {
      id: 15,
      title: "Everherb Giloy Tulsi Juice - Strengthens Body",
      MRP: "MRP ₹399.00",
      price: "₹199.50",
      discount: "(50%)",
      image: require("./"),
    },
  ],
};
